[package]
name = "embedded-resources"
version = "0.1.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.48", features = ["full"] }

[lib]
proc-macro = true
